float3 rayStep = viewDir * -1;
float4 inputTex = Texture2DSample(textObject, texObjectSampler, uv);

# 做一个特效，使得贴图好像深入了一样
int lv = 25;
for(int i = 0;
    i < lv;
    i ++) {
    if(inputTex.r > 0.1;
        && inputTex.g > 0.1 && inputTex.b > 0.1) {
        return float3(i, 0, 0)
    }
    uv += rayStep * 0.15;
    inputTex = Texture2DSample(texObject, texObjectSampler, uv.xy);
}
return inputTex;
