
// 画圆圈

float result = 0;

for(int i = 0;i < count;i ++) {
    // 计算弧度，因为shader用弧度，均分成count份
    float angle = (i / count) * 2 * 3.14;

    float2 normal = float2(cos(angle), sin(angle));// 单位向量

    float2 pos = center + radius * normal; // 实际位置

    // 计算当前像素到小圆点的距离
    // 如果距离小于 size，返回 1.0，否则返回 0.0
    // 这个比较结果在 HLSL 中会隐式转换为浮点数（1.0 或 0.0）
    // 所以小于size的时候就是白色，size取值0-1，1就是占满贴图
    result += length(pos - uv) < size;
}

return result;